### ISSUE TITLE
"Create Account" and "Forgot Password" Text are far apart from the Login Button

### ISSUE THREAD

**Issue by khalidelho** [zyadelgohary/QConnect#38]
![image](https://user-images.githubusercontent.com/47620535/64657937-6a418e80-d3ea-11e9-8cbc-d3681722caac.png)

**Comment by zyadelgohary** [comment]
We want it to look like this so that the user doesn't click log in on accident when try to choose create account. I already fixed a previous issue like this by making the text a little bigger and moving the text itself a little up, but we shouldn't have it scrunched up against the button
